# 3장 파이썬 핵심 문법

In [ ]:
pr

## 3.9 파일 입출력

In [ ]:
f=open('name.txt')
data=f.read()
print(data)
f.close()

홍길동
홍이동
홍삼동

In [ ]:
f=open('name.txt')
data=f.readline()
print(data)
f.close()

홍길동

In [ ]:
f=open('name.txt')
while True:
    data=f.readline()
    if not data:break
    print(data,end='')
f.close()

홍길동
홍이동
홍삼동

In [ ]:
f=open('name.txt')
data=f.readlines()
print(data,end='')
f.close()

['홍길동\n', '홍이동\n', '홍삼동']

In [ ]:
f=open('name.txt')
data=f.readlines()
for line in data:
    print(line,end='')
f.close()

홍길동
홍이동
홍삼동

In [ ]:
with open('name.txt') as f:
    data=f.readlines()
    print(data,end='')

['홍길동\n', '홍이동\n', '홍삼동']

In [ ]:
f=open('club.txt','w')

while True:
    name=input('이름: ')
    if not name:break
    f.write(name)
f.close()

이름: 김유미
이름: 구웅
이름: 유바비
이름:

In [ ]:
f=open('club.txt','w')

while True:
    name=input('이름: ')
    if not name:break
    f.write(name+'\n')
f.close()

이름: 김유미
이름: 구웅
이름: 유바비
이름:

In [ ]:
f=open('club.txt','a')

while True:
    name=input('이름: ')
    if not name:break
    f.write(name+'\n')
f.close()

이름: 루비
이름: 새이
이름:

In [ ]:
f=open('test.txt','r')

while True:
    name=input('이름: ')
    if not name:break
    f.write(name+'\n')
f.close()

FileNotFoundError: ignored

In [ ]:
import os.path

fname=input('파일명: ')
fname=fname+'.txt'
if os.path.exists(fname): # os.path.isfile(fname)
    f=open(fname,'r')
    data=f.read()
    print(data,end='')
    f.close()
else:
    print('{} 파일이 없습니다.'.format(fname))

파일명: test
test.txt 파일이 없습니다.

In [ ]:
fname=input('파일명: ')
fname=fname+'.txt'
try:
    f=open(fname)
    data=f.read()
    print(data,end='')
    f.close()
except:
    print('{} 파일이 없습니다.'.format(fname))

파일명: test
test.txt 파일이 없습니다.

In [ ]:
import pandas as pd
my_file = pd.read_csv('my_file.csv')
my_file.head()

   이름  중간  기말  과제   출석  학점  가산점
0  유미  95  87  95  100  A+    2
1  구웅  88  90  90   70   A   10
2  바비  72  83  80   72  B+    5

In [ ]:
new_pd = pd.DataFrame([['루비',80,80,75,90,'B+',0]])
new_pd

    0   1   2   3   4   5  6
0  루비  80  80  75  90  B+  0

In [ ]:
new_pd.to_csv('my_file.csv', mode='a', header=False, index=False)
my_file = pd.read_csv('my_file.csv')
my_file.head()

   이름  중간  기말  과제   출석  학점  가산점
0  유미  95  87  95  100  A+    2
1  구웅  88  90  90   70   A   10
2  바비  72  83  80   72  B+    5
3  루비  80  80  75   90  B+    0

In [ ]:
import pandas as pd
my_addr = pd.read_excel('my_addr.xlsx')
my_addr.head()

    이름            연락처            이메일
0  이순신  010-1234-1234   lee@test.com
1  강감찬  010-1111-1111  kang@test.com
2  홍길동  010-2222-2222  hong@test.com

In [ ]:
my_addr = my_addr.append([{'이름':'유관순','연락처':'010-3333-3333','이메일':'you@test.com'}])
my_addr

    이름            연락처            이메일
0  이순신  010-1234-1234   lee@test.com
1  강감찬  010-1111-1111  kang@test.com
2  홍길동  010-2222-2222  hong@test.com
0  유관순  010-3333-3333   you@test.com

In [ ]:
my_addr.to_excel('my_addr.xlsx',index=False)
my_addr = pd.read_excel('my_addr.xlsx')
my_addr.head()

    이름            연락처            이메일
0  이순신  010-1234-1234   lee@test.com
1  강감찬  010-1111-1111  kang@test.com
2  홍길동  010-2222-2222  hong@test.com
3  유관순  010-3333-3333   you@test.com